"""Dataset card (03 §3.9). Written by ``build_dataset``, not edited by hand."""
from __future__ import annotations

from collections import Counter
from pathlib import Path

_CLASSES = [
    "M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M10",
    "D01", "D02", "D03", "D04", "D05", "D06", "D07", "D08",
    "OTHER", "CORRECT",
]


def write_card(path, rows, report):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_render(rows, report), encoding="utf-8")


def _render(rows, report):
    by_label = Counter(row["label"] for row in rows)
    by_source = Counter(row["source"] for row in rows)
    by_label_source = Counter((row["label"], row["source"]) for row in rows)
    by_problem = Counter(row["problem_id"] for row in rows)
    lines = []
    add = lines.append
    add("# Dataset card")
    add("")
    add("Generated by `ml.generate.card` from `ml/data/dataset.jsonl`.")
    add("This file is the synthetic training corpus (sources A, E and AMB).")
    add("It is a hackathon demo and a research prototype. It is not for grading students.")
    add("")
    add("## Counts")
    add("")
    add(f"- Rows: **{len(rows)}**")
    add(f"- Main (P*): **{report['domain_main']}**")
    add(f"- DSA (Q*): **{report['domain_dsa']}**")
    add(f"- Source A: **{by_source['A']}**, E: **{by_source['E']}**, AMB: **{by_source['AMB']}**")
    add(f"- Two-bug rows: **{report['two_bug']}**")
    add(f"- Passes-by-luck (not in this file): **{report['luck_rows']}** in `ml/data/passes_by_luck.jsonl`")
    add("")
    add("### Effective N")
    add("")
    add(f"- `n_rows`: **{report['n_rows']}**")
    add(f"- `n_unique_hash`: **{report['n_unique_hash']}**")
    add(f"- `n_unique(problem, variant, op_id)`: **{report['n_unique_pvo']}**")
    add("")
    add("Augmentations that only change comments, spacing or parentheses share a normalised hash, so `n_unique_hash` is smaller than `n_rows`.")
    add("")
    add("### Per class")
    add("")
    add("| class | rows | A | E | AMB |")
    add("|---|---:|---:|---:|---:|")
    for label in _CLASSES:
        add(
            f"| {label} | {by_label[label]} | {by_label_source[(label, 'A')]} "
            f"| {by_label_source[(label, 'E')]} | {by_label_source[(label, 'AMB')]} |"
        )
    add("")
    add("### Per problem")
    add("")
    add("| problem | split | domain | rows |")
    add("|---|---|---|---:|")
    meta = {}
    for row in rows:
        meta[row["problem_id"]] = (row["split"], "dsa" if row["problem_id"].startswith("Q") else "main")
    for problem_id in sorted(by_problem):
        split, domain = meta[problem_id]
        add(f"| {problem_id} | {split} | {domain} | {by_problem[problem_id]} |")
    add("")
    add("### Class × source × problem")
    add("")
    add("Non-zero cells only.")
    add("")
    add("| problem | class | source | rows |")
    add("|---|---|---|---:|")
    cell = Counter((row["problem_id"], row["label"], row["source"]) for row in rows)
    for problem_id, label, source in sorted(cell):
        add(f"| {problem_id} | {label} | {source} | {cell[(problem_id, label, source)]} |")
    add("")
    add("## Operator catalogue and drop rates")
    add("")
    add("Drop rate is `(attempts − kept) / attempts` on the unaugmented mutant.")
    add("Passes-by-luck counts as a drop from training. Style-augmentation rejects are separate and do not move this rate.")
    add("An operator over 40% is listed as high-drop. C3 does not edit C1/C2 operators; verified rows from those operators are still kept.")
    add("")
    add("| op_id | attempts | kept | luck | drop rate |")
    add("|---|---:|---:|---:|---:|")
    for op_id, attempts, kept, luck, rate in report["operators"]:
        flag = " **" if rate is not None and rate > 0.40 else ""
        rate_text = "—" if rate is None else f"{rate:.0%}{flag}"
        add(f"| `{op_id}` | {attempts} | {kept} | {luck} | {rate_text} |")
    add("")
    zeros = report["zero_kept"]
    add("Operators with zero kept training rows:")
    add("")
    if zeros:
        for op_id, reason in zeros:
            add(f"- `{op_id}` — {reason}")
    else:
        add("- none")
    add("")
    add("## Verification")
    add("")
    add("A row is kept only when all of the following hold:")
    add("")
    add("1. The interpreter parses it (`run_tests`, backend `interp`). `parse_error` and `unsupported` are drops. A step-cap timeout is a failed test.")
    add("2. `CORRECT` passes every test.")
    add("3. A class row fails at least one test and `holds(op_id)` is true. `holds` is `holds_dsa` for a DSA op_id and `holds_main` otherwise. `oth_*` is always false.")
    add("4. `OTHER` fails at least one test and no class predicate holds.")
    add("5. `d05_unreachable_base` also needs an odd scalar test argument.")
    add("6. Two-bug rows (bounded sample, source E) need both predicates and must fail a test that each single mutant also fails.")
    add("")
    add("Rows that were built as a misconception but pass every test are written to `ml/data/passes_by_luck.jsonl` with `verified.passes_by_luck` true. They are not in `dataset.jsonl` and they are not part of the row count above.")
    add("")
    add("## Ambiguity")
    add("")
    add("The hash is a normalised AST: comments dropped, `debug=true` printfs dropped, increments canonicalised, locals renamed to `v0, v1, …`, entry names left in place, braces reprinted.")
    add("Groups whose labels are exactly `{M01, M08}` are source `AMB` with `soft_label` 0.5/0.5.")
    add(f"AMB rows: **{by_source['AMB']}**. Ambiguity groups: **{report['amb_groups']}**.")
    add("")
    if report["clashes"]:
        add("Other label clashes (not soft-labelled; the minority label in the group was dropped):")
        add("")
        for line in report["clashes"]:
            add(f"- {line}")
    else:
        add("No label clash other than `{M01, M08}`.")
    add("")
    add("## Augmentations")
    add("")
    add("`rename`, `brace_style`, `incr_form`, `decl_hoist`, `comments`, `debug_printf`, `spacing`, `redundant_parens`, `unused_var`.")
    add("Each mutant samples from that list. Comments include English and Hinglish templates.")
    add("`debug_printf` inserts `printf(\"debug=true %d\\n\", …)`, which the hash drops and the tests re-run.")
    add(f"Augmentation candidates rejected after re-verification: **{report['aug_rejects']}**.")
    add("")
    if report["relaxed"]:
        add("Caps are 15 rows per `(problem, op_id)` and 6 augmentations per `(problem, variant, op_id)` when that already reaches the class aim. Classes whose sites cannot fill the aim under those caps use a higher cap, still round-robin across problems and operators, and still stop at the aim ceiling (M 550, D 400):")
        add("")
        for label, cap_po, cap_aug, groups in report["relaxed"]:
            add(f"- `{label}`: cap raised above 15 ({groups} problem/op groups; per-group ceiling {cap_po})")
    else:
        add("Caps: at most 15 rows per `(problem, op_id)` and 6 augmentations per `(problem, variant, op_id)`.")
    add("")
    add("## Near-miss share")
    add("")
    correct = by_label["CORRECT"]
    near = by_label_source[("CORRECT", "E")]
    share = (near / correct) if correct else 0.0
    add(f"CORRECT rows: **{correct}**. Source E (near-miss and weird-but-valid): **{near}** ({share:.0%}).")
    add("Near-miss rewrites that still pass every test include `i <= n - 1`, 1-based `a[i - 1]` traversal, `int t; t = 0;`, Yoda conditions, unbraced single statements, a redundant `x = x + 0`, debug printf with the return left in place, countdown reversal, swap-temp order, midpoint form, bubble inner bound, string terminator spelling, and an unused array.")
    add("Skipped as too brittle for this run: accumulator-parameter recursion, a `found` flag plus `break`, `else continue`, and a bubble `swapped` early-exit. Feature-dropout rows (NaN trace groups) belong to training, not to this file.")
    add("")
    add("## Passes by luck")
    add("")
    add("`amb_pair_bound` on Q11 cv1 and cv2 (`i < n - 1` with `a[i + 1]`) still passes: the extra iteration writes `a[n - 1]` and the saved `first` overwrites it (notes/C2.md). Those rows are in the passes-by-luck pool, not in the training file.")
    add(f"Luck rows by operator: {report['luck_by_op']}.")
    add("")
    add("## Known biases")
    add("")
    add("- Every training row is an author-written template or a mechanical edit of one. No real learner programs are in this file.")
    add("- Style variety is a fixed list (a few identifier pools, eight comment lines, K&R / Allman / no braces). That is one cohort's habits, repeated.")
    add("- Operators with no bank site (`m02_update_in_branch`, `m04_int_literal`, `m06_while_assign`, `d08_array_eq`) contribute no rows. D-classes and a few M-classes have too few sites to hit 250–550 rows at 15 per problem, so their cap is raised and those templates are over-represented. `n_unique_hash` is the fairer count.")
    add("- Held-out problems (P04, P09, P13, Q04, Q09, Q16) are in the file with `split: holdout_problem`. Training must drop that split.")
    add("- `op_variant` equals `op_id`.")
    add("")
    add("## ITSP")
    add("")
    add("This file does not contain the ITSP slice. The plan treats ITSP as an evaluation-only set: cite the FSE 2017 Prutor paper and do not redistribute student programs. The upstream repository also carries an MIT licence (see notes/X1.md); either reading still keeps those programs out of training and out of this card's row count.")
    add("")
    add("## R protocol")
    add("")
    add("R-blind (40 items, written without the operator list) and R-team (30 items) are not in this file. A second rater labels each item from the code alone; the report for that set is percent agreement and Cohen's κ. Disagreements keep both raw labels. κ is not computed here because this corpus has no second rater: the label is the operator that built the row.")
    add("")
    return "\n".join(lines) + "\n"
